/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RegelnRouteImport } from './routes/regeln'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as GamemodesRouteImport } from './routes/gamemodes'
import { Route as BeitretenRouteImport } from './routes/beitreten'
import { Route as IndexRouteImport } from './routes/index'

const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RegelnRoute = RegelnRouteImport.update({
  id: '/regeln',
  path: '/regeln',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const GamemodesRoute = GamemodesRouteImport.update({
  id: '/gamemodes',
  path: '/gamemodes',
  getParentRoute: () => rootRouteImport,
} as any)
const BeitretenRoute = BeitretenRouteImport.update({
  id: '/beitreten',
  path: '/beitreten',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beitreten': typeof BeitretenRoute
  '/gamemodes': typeof GamemodesRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/regeln': typeof RegelnRoute
  '/support': typeof SupportRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beitreten': typeof BeitretenRoute
  '/gamemodes': typeof GamemodesRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/regeln': typeof RegelnRoute
  '/support': typeof SupportRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beitreten': typeof BeitretenRoute
  '/gamemodes': typeof GamemodesRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/regeln': typeof RegelnRoute
  '/support': typeof SupportRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beitreten'
    | '/gamemodes'
    | '/leaderboards'
    | '/regeln'
    | '/support'
    | '/ueber-uns'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beitreten'
    | '/gamemodes'
    | '/leaderboards'
    | '/regeln'
    | '/support'
    | '/ueber-uns'
  id:
    | '__root__'
    | '/'
    | '/beitreten'
    | '/gamemodes'
    | '/leaderboards'
    | '/regeln'
    | '/support'
    | '/ueber-uns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeitretenRoute: typeof BeitretenRoute
  GamemodesRoute: typeof GamemodesRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  RegelnRoute: typeof RegelnRoute
  SupportRoute: typeof SupportRoute
  UeberUnsRoute: typeof UeberUnsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regeln': {
      id: '/regeln'
      path: '/regeln'
      fullPath: '/regeln'
      preLoaderRoute: typeof RegelnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamemodes': {
      id: '/gamemodes'
      path: '/gamemodes'
      fullPath: '/gamemodes'
      preLoaderRoute: typeof GamemodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beitreten': {
      id: '/beitreten'
      path: '/beitreten'
      fullPath: '/beitreten'
      preLoaderRoute: typeof BeitretenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeitretenRoute: BeitretenRoute,
  GamemodesRoute: GamemodesRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  RegelnRoute: RegelnRoute,
  SupportRoute: SupportRoute,
  UeberUnsRoute: UeberUnsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
